spring.application.name=trackingpixel

# H2 database settings
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Server Port
server.port=8080

# API Key
#ipgeo.api.key=523a004b91c84d8b93ed6d2aaba4e838

#server.forward-headers-strategy=framework


